version: '3'

volumes:
    data:
 
networks:
    my-network:
        driver: bridge
    
services:
    web:
        image: grafana/grafana:7.0.0
        volumes:
            - ./web/datasources/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
            - ./web/dashboards:/etc/grafana/provisioning/dashboards
        ports:
            - 18000:3000
        networks:
            - my-network
    
    database:
        image: postgres:9.6
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
        volumes:
            - ./database:/database
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./data:/var/lib/postgresql/data
        ports:
            - 18001:5432
        networks:
            - my-network
 
    processing:
        image: python:3.7.2
        volumes:
            - ./processing:/processing
        working_dir: /processing
        command: bash ./start_processing.sh
        networks:
            - my-network