#----------------------------------------------------------------------------------------------------------
#
#			Name: Eng. William da Rosa Frohlich
#
#			Project: Database and Grafana for BITalino Server
#
#			Date: 2020.06.13
#
#----------------------------------------------------------------------------------------------------------
#----------			Version			----------

version: '3'

#----------------------------------------------------------------------------------------------------------
#----------			Volumes			----------

volumes:
    data:

#----------------------------------------------------------------------------------------------------------
#----------			Networks			----------
 
networks:
    my-network:
        driver: bridge

#----------------------------------------------------------------------------------------------------------
#----------			Services			----------
    
services:
    web:
        image: grafana/grafana:7.0.0
        volumes:
            - ./web/datasources/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml # Link with the database
            - ./web/dashboards:/etc/grafana/provisioning/dashboards # Insert and initialize the dashboards
        ports:
            - 18000:3000
        networks:
            - my-network
    
    database:
        image: postgres:9.6
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
        volumes:
            - ./database:/database
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql # Define the database and the tables
        ports:
            - 18001:5432
        networks:
            - my-network
 
    processing:
        image: python:3.8.3
        volumes:
            - ./processing:/usr/src/processing
        ports:
            - 18101:18101/udp
            - 18102:18102/udp
            - 18103:18103/udp
            - 18106:18106/udp
        working_dir: /usr/src/processing
        command: bash ./start_processing.sh
        networks:
            - my-network